### ISSUE TITLE
when importing get typescript errors 

### ISSUE THREAD

**Issue by closet6** [rubiin/validator#1]
**deno version:**
deno 1.0.2
v8 8.4.300
typescript 3.9.2

**command:**
`deno cache https://deno.land/x/validatorjs/mod.ts`

**errors:**
```
error: TS7053 [ERROR]: Element implicitly has an 'any' type because expression of type 'string' can't be used to index type '{ X: number; Y: number; Z: number; }'.
  No index signature with a parameter of type 'string' was found on type '{ X: number; Y: number; Z: number; }'.
    const number : any = sanitized.slice(0, -1).replace(/[X,Y,Z]/g, char => charsValue[char]);
                                                                            ~~~~~~~~~~~~~~~~
    at https://deno.land/x/validatorjs/src/lib/isIdentityCard.ts:29:77

TS7006 [ERROR]: Parameter 'str' implicitly has an 'any' type.
  'he-IL': (str) => {
            ~~~
    at https://deno.land/x/validatorjs/src/lib/isIdentityCard.ts:33:13

TS7006 [ERROR]: Parameter 'str' implicitly has an 'any' type.
  'ar-TN': (str) => {
            ~~~
    at https://deno.land/x/validatorjs/src/lib/isIdentityCard.ts:54:13

TS7006 [ERROR]: Parameter 'str' implicitly has an 'any' type.
  'zh-CN': (str) => {
            ~~~
    at https://deno.land/x/validatorjs/src/lib/isIdentityCard.ts:66:13

TS7053 [ERROR]: Element implicitly has an 'any' type because expression of type 'number' can't be used to index type '{ 11: string; 12: string; 13: string; 14: string; 15: string; 21: string; 22: string; 23: string; 31: string; 32: string; 33: string; 34: string; 35: string; 36: string; 37: string; 41: string; 42: string; 43: string; ... 16 more ...; 91: string; }'.
  No index signature with a parameter of type 'number' was found on type '{ 11: string; 12: string; 13: string; 14: string; 15: string; 21: string; 22: string; 23: string; 31: string; 32: string; 33: string; 34: string; 35: string; 36: string; 37: string; 41: string; 42: string; 43: string; ... 16 more ...; 91: string; }'.
      return !!provinceAndCitys[Number.parseInt(addressCode.substring(0, 2))];
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://deno.land/x/validatorjs/src/lib/isIdentityCard.ts:113:16

TS7006 [ERROR]: Parameter 'birDayCode' implicitly has an 'any' type.
    const checkBirthDayCode = (birDayCode) => {
                               ~~~~~~~~~~
    at https://deno.land/x/validatorjs/src/lib/isIdentityCard.ts:116:32

TS2769 [ERROR]: No overload matches this call.
  Overload 1 of 3, '(callbackfn: (previousValue: string, currentValue: string, currentIndex: number, array: string[]) => string, initialValue: string): string', gave the following error.
    Argument of type '(sum: number, number: string, index: number) => number | boolean' is not assignable to parameter of type '(previousValue: string, currentValue: string, currentIndex: number, array: string[]) => string'.
      Types of parameters 'sum' and 'previousValue' are incompatible.
        Type 'string' is not assignable to type 'number'.
  Overload 2 of 3, '(callbackfn: (previousValue: number, currentValue: string, currentIndex: number, array: string[]) => number, initialValue: number): number', gave the following error.
    Argument of type '(sum: number, number: string, index: number) => number | boolean' is not assignable to parameter of type '(previousValue: number, currentValue: string, currentIndex: number, array: string[]) => number'.
      Type 'number | boolean' is not assignable to type 'number'.
        Type 'false' is not assignable to type 'number'.
    return Array.from(sanitized).reduce((sum, number, index) => {
                                        ~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://deno.land/x/validatorjs/src/lib/isIdentityCard.ts:218:41

TS7053 [ERROR]: Element implicitly has an 'any' type because expression of type 'string' can't be used to index type '{ A: number; B: number; C: number; D: number; E: number; F: number; G: number; H: number; I: number; J: number; K: number; L: number; M: number; N: number; O: number; P: number; Q: number; R: number; S: number; T: number; U: number; ... 4 more ...; Z: number; }'.
  No index signature with a parameter of type 'string' was found on type '{ A: number; B: number; C: number; D: number; E: number; F: number; G: number; H: number; I: number; J: number; K: number; L: number; M: number; N: number; O: number; P: number; Q: number; R: number; S: number; T: number; U: number; ... 4 more ...; Z: number; }'.
        const code = ALPHABET_CODES[number];
                     ~~~~~~~~~~~~~~~~~~~~~~
    at https://deno.land/x/validatorjs/src/lib/isIdentityCard.ts:220:22

TS7053 [ERROR]: Element implicitly has an 'any' type because expression of type 'string' can't be used to index type '{ ES: (str: string) => boolean; 'he-IL': (str: any) => boolean; 'ar-TN': (str: any) => boolean; 'zh-CN': (str: any) => boolean; 'zh-TW': (str: string) => string | false; }'.
  No index signature with a parameter of type 'string' was found on type '{ ES: (str: string) => boolean; 'he-IL': (str: any) => boolean; 'ar-TN': (str: any) => boolean; 'zh-CN': (str: any) => boolean; 'zh-TW': (str: string) => string | false; }'.
    return validators[locale](str);
           ~~~~~~~~~~~~~~~~~~
    at https://deno.land/x/validatorjs/src/lib/isIdentityCard.ts:237:12

TS7053 [ERROR]: Element implicitly has an 'any' type because expression of type 'string' can't be used to index type '{ ES: (str: string) => boolean; 'he-IL': (str: any) => boolean; 'ar-TN': (str: any) => boolean; 'zh-CN': (str: any) => boolean; 'zh-TW': (str: string) => string | false; }'.
  No index signature with a parameter of type 'string' was found on type '{ ES: (str: string) => boolean; 'he-IL': (str: any) => boolean; 'ar-TN': (str: any) => boolean; 'zh-CN': (str: any) => boolean; 'zh-TW': (str: string) => string | false; }'.
        const validator = validators[key];
                          ~~~~~~~~~~~~~~~
    at https://deno.land/x/validatorjs/src/lib/isIdentityCard.ts:243:27
```

**Comment by rubiin** [comment]
Fixed :)

**Comment by closet6** [comment]
nice job, thanks for the quick turnaround.
confirmed with:
`deno cache -r https://deno.land/x/validatorjs/mod.ts `

**Comment by rubiin** [comment]
as the codebase is still a work in progress, issues are ineveitable :)
